main:
  - name: Bio
    url: /
    weight: 10

  - name: Research
    url: /publications/
    weight: 20

  - name: Teaching
    url: /teaching/
    weight: 30

  - name: CV
    url: /files/CV_SahilRavgotra.pdf
    weight: 40
