main:
  - name: Bio
    url: /
    weight: 10

  - name: Research
    url: /publication/
    weight: 20

  - name: Teaching
    url: /teaching/
    weight: 30

  - name: CV
    url: "/static/uploads/sahilcv.pdf"
    weight: 40
