main:
  - name: Bio
    url: /
    weight: 10

  - name: Research
    url: /publications/
    weight: 20

  - name: Teaching
    url: /teaching/
    weight: 30

  - name: CV
    url: /uploads/sahil_cv.pdf
    weight: 40
