# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

favicon: "media/icon.png"
i_am_a_sponsor: true 

# Appearance
appearance:
  mode: system
  color: emerald

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: 'Macroeconomist'
    org_name: 'University of Texas at Austin'
    description: 'Macroeconomist at the University of Texas at Austin.'
    twitter: 'GetResearchDev'
    i_am_a_sponsor: true
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Sahil Ravgotra"

# Site footer
footer:
  copyright:
    notice: '© {year} Sahil Ravgotra. All rights reserved.'
    license:
      enable: true
      allow_derivatives: false
      share_alike: false
      allow_commercial: false
    

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false



custom_scss:
  - scss/custom.scss
